-- 005_seed_tags.sql
-- Seed data for tags table with 200 specific tags across 10 categories

INSERT INTO tags (slug, name_tr, name_en, category, icon, sort_order) VALUES
-- game (25)
('minecraft', 'Minecraft', 'Minecraft', 'game', '⛏️', 1),
('lol', 'League of Legends', 'League of Legends', 'game', '⚔️', 2),
('valorant', 'Valorant', 'Valorant', 'game', '🔫', 3),
('cs2', 'Counter-Strike 2', 'Counter-Strike 2', 'game', '💣', 4),
('gta', 'Grand Theft Auto', 'Grand Theft Auto', 'game', '🚗', 5),
('fortnite', 'Fortnite', 'Fortnite', 'game', '🚌', 6),
('roblox', 'Roblox', 'Roblox', 'game', '🧱', 7),
('genshin-impact', 'Genshin Impact', 'Genshin Impact', 'game', '✨', 8),
('fifa', 'FIFA', 'FIFA', 'game', '⚽', 9),
('elden-ring', 'Elden Ring', 'Elden Ring', 'game', '💍', 10),
('zelda', 'Zelda', 'Zelda', 'game', '🗡️', 11),
('mario', 'Mario', 'Mario', 'game', '🍄', 12),
('pokemon', 'Pokémon', 'Pokémon', 'game', '🔴', 13),
('among-us', 'Among Us', 'Among Us', 'game', '👾', 14),
('clash-royale', 'Clash Royale', 'Clash Royale', 'game', '👑', 15),
('pubg', 'PUBG', 'PUBG', 'game', '🪂', 16),
('apex-legends', 'Apex Legends', 'Apex Legends', 'game', '🏆', 17),
('dota-2', 'Dota 2', 'Dota 2', 'game', '🧙', 18),
('overwatch', 'Overwatch', 'Overwatch', 'game', '🦸', 19),
('god-of-war', 'God of War', 'God of War', 'game', '🪓', 20),
('the-sims', 'The Sims', 'The Sims', 'game', '💎', 21),
('stardew-valley', 'Stardew Valley', 'Stardew Valley', 'game', '🌾', 22),
('red-dead-redemption', 'Red Dead Redemption', 'Red Dead Redemption', 'game', '🤠', 23),
('animal-crossing', 'Animal Crossing', 'Animal Crossing', 'game', '🏕️', 24),
('cyberpunk-2077', 'Cyberpunk 2077', 'Cyberpunk 2077', 'game', '🦾', 25),

-- music (20)
('pop', 'Pop', 'Pop', 'music', '🎤', 1),
('rock', 'Rock', 'Rock', 'music', '🎸', 2),
('hip-hop', 'Hip-Hop', 'Hip-Hop', 'music', '🎧', 3),
('rnb', 'R&B', 'R&B', 'music', '🎙️', 4),
('jazz', 'Caz', 'Jazz', 'music', '🎷', 5),
('classical-music', 'Klasik Müzik', 'Classical Music', 'music', '🎻', 6),
('edm', 'Elektronik / EDM', 'Electronic / EDM', 'music', '🎛️', 7),
('k-pop', 'K-Pop', 'K-Pop', 'music', '🫰', 8),
('metal', 'Metal', 'Metal', 'music', '🤘', 9),
('indie', 'Indie', 'Indie', 'music', '🎹', 10),
('reggae', 'Reggae', 'Reggae', 'music', '🌴', 11),
('country', 'Country', 'Country', 'music', '🤠', 12),
('lo-fi', 'Lo-Fi', 'Lo-Fi', 'music', '📼', 13),
('blues', 'Blues', 'Blues', 'music', '🎵', 14),
('punk', 'Punk', 'Punk', 'music', '🧷', 15),
('latin', 'Latin', 'Latin', 'music', '💃', 16),
('turkish-pop', 'Türkçe Pop', 'Turkish Pop', 'music', '🇹🇷', 17),
('arabesk', 'Arabesk', 'Arabesque', 'music', '💔', 18),
('rap', 'Rap', 'Rap', 'music', '🗣️', 19),
('turku', 'Türkü', 'Turkish Folk', 'music', '🪕', 20),

-- language (25)
('english', 'İngilizce', 'English', 'language', '🇬🇧', 1),
('mandarin', 'Çince / Mandarin', 'Mandarin', 'language', '🇨🇳', 2),
('hindi', 'Hintçe', 'Hindi', 'language', '🇮🇳', 3),
('spanish', 'İspanyolca', 'Spanish', 'language', '🇪🇸', 4),
('french', 'Fransızca', 'French', 'language', '🇫🇷', 5),
('arabic', 'Arapça', 'Arabic', 'language', '🇸🇦', 6),
('bengali', 'Bengalce', 'Bengali', 'language', '🇧🇩', 7),
('portuguese', 'Portekizce', 'Portuguese', 'language', '🇵🇹', 8),
('russian', 'Rusça', 'Russian', 'language', '🇷🇺', 9),
('japanese', 'Japonca', 'Japanese', 'language', '🇯🇵', 10),
('german', 'Almanca', 'German', 'language', '🇩🇪', 11),
('korean', 'Korece', 'Korean', 'language', '🇰🇷', 12),
('vietnamese', 'Vietnamca', 'Vietnamese', 'language', '🇻🇳', 13),
('turkish', 'Türkçe', 'Turkish', 'language', '🇹🇷', 14),
('italian', 'İtalyanca', 'Italian', 'language', '🇮🇹', 15),
('thai', 'Tay Dili', 'Thai', 'language', '🇹🇭', 16),
('persian', 'Farsça', 'Persian', 'language', '🇮🇷', 17),
('polish', 'Lehçe', 'Polish', 'language', '🇵🇱', 18),
('ukrainian', 'Ukraynaca', 'Ukrainian', 'language', '🇺🇦', 19),
('romanian', 'Rumence', 'Romanian', 'language', '🇷🇴', 20),
('dutch', 'Felemenkçe', 'Dutch', 'language', '🇳🇱', 21),
('greek', 'Yunanca', 'Greek', 'language', '🇬🇷', 22),
('czech', 'Çekçe', 'Czech', 'language', '🇨🇿', 23),
('swedish', 'İsveççe', 'Swedish', 'language', '🇸🇪', 24),
('hungarian', 'Macarca', 'Hungarian', 'language', '🇭🇺', 25),

-- subject (30)
('math', 'Matematik', 'Math', 'subject', '➗', 1),
('physics', 'Fizik', 'Physics', 'subject', '⚛️', 2),
('chemistry', 'Kimya', 'Chemistry', 'subject', '🧪', 3),
('biology', 'Biyoloji', 'Biology', 'subject', '🧬', 4),
('history', 'Tarih', 'History', 'subject', '📜', 5),
('geography', 'Coğrafya', 'Geography', 'subject', '🌍', 6),
('literature', 'Edebiyat', 'Literature', 'subject', '📚', 7),
('philosophy', 'Felsefe', 'Philosophy', 'subject', '🤔', 8),
('sociology', 'Sosyoloji', 'Sociology', 'subject', '🤝', 9),
('psychology', 'Psikoloji', 'Psychology', 'subject', '🧠', 10),
('economics', 'Ekonomi', 'Economics', 'subject', '📈', 11),
('law', 'Hukuk', 'Law', 'subject', '⚖️', 12),
('medicine', 'Tıp', 'Medicine', 'subject', '⚕️', 13),
('engineering', 'Mühendislik', 'Engineering', 'subject', '⚙️', 14),
('architecture', 'Mimarlık', 'Architecture', 'subject', '🏛️', 15),
('astronomy', 'Astronomi', 'Astronomy', 'subject', '🔭', 16),
('statistics', 'İstatistik', 'Statistics', 'subject', '📊', 17),
('accounting', 'Muhasebe', 'Accounting', 'subject', '🧾', 18),
('political-science', 'Siyaset Bilimi', 'Political Science', 'subject', '🗳️', 19),
('linguistics', 'Dilbilim', 'Linguistics', 'subject', '🗣️', 20),
('archaeology', 'Arkeoloji', 'Archaeology', 'subject', '🏺', 21),
('anthropology', 'Antropoloji', 'Anthropology', 'subject', '🦴', 22),
('neuroscience', 'Nörobilim', 'Neuroscience', 'subject', '🧠', 23),
('ecology', 'Ekoloji', 'Ecology', 'subject', '🌱', 24),
('genetics', 'Genetik', 'Genetics', 'subject', '🧬', 25),
('pharmacology', 'Farmakoloji', 'Pharmacology', 'subject', '💊', 26),
('anatomy', 'Anatomi', 'Anatomy', 'subject', '💀', 27),
('biomedical', 'Biyomedikal', 'Biomedical', 'subject', '🔬', 28),
('art-history', 'Sanat Tarihi', 'Art History', 'subject', '🎨', 29),
('musicology', 'Müzikoloji', 'Musicology', 'subject', '🎵', 30),

-- tech (25)
('python', 'Python', 'Python', 'tech', '🐍', 1),
('javascript', 'JavaScript', 'JavaScript', 'tech', '🟨', 2),
('java', 'Java', 'Java', 'tech', '☕', 3),
('cpp', 'C++', 'C++', 'tech', '➕', 4),
('web-dev', 'Web Geliştirme', 'Web Development', 'tech', '🌐', 5),
('mobile-dev', 'Mobil Geliştirme', 'Mobile Development', 'tech', '📱', 6),
('ai', 'Yapay Zeka', 'AI', 'tech', '🤖', 7),
('machine-learning', 'Makine Öğrenmesi', 'Machine Learning', 'tech', '🧠', 8),
('data-science', 'Veri Bilimi', 'Data Science', 'tech', '📊', 9),
('cybersecurity', 'Siber Güvenlik', 'Cybersecurity', 'tech', '🔒', 10),
('blockchain', 'Blockchain', 'Blockchain', 'tech', '🔗', 11),
('cloud-computing', 'Bulut Bilişim', 'Cloud Computing', 'tech', '☁️', 12),
('devops', 'DevOps', 'DevOps', 'tech', '♾️', 13),
('ux-ui', 'UX/UI Tasarım', 'UX/UI Design', 'tech', '🎨', 14),
('robotics', 'Robotik', 'Robotics', 'tech', '🦾', 15),
('iot', 'IoT', 'IoT', 'tech', '📶', 16),
('game-dev', 'Oyun Geliştirme', 'Game Dev', 'tech', '🎮', 17),
('linux', 'Linux', 'Linux', 'tech', '🐧', 18),
('flutter', 'Flutter', 'Flutter', 'tech', '🦋', 19),
('react', 'React', 'React', 'tech', '⚛️', 20),
('swift', 'Swift', 'Swift', 'tech', '🦅', 21),
('kotlin', 'Kotlin', 'Kotlin', 'tech', '🟪', 22),
('sql', 'SQL', 'SQL', 'tech', '💾', 23),
('arduino', 'Arduino', 'Arduino', 'tech', '⚡', 24),
('3d-printing', '3D Baskı', '3D Printing', 'tech', '🖨️', 25),

-- creative (20)
('drawing', 'Çizim', 'Drawing', 'creative', '✏️', 1),
('digital-art', 'Dijital Sanat', 'Digital Art', 'creative', '🖊️', 2),
('photography', 'Fotoğrafçılık', 'Photography', 'creative', '📷', 3),
('video-editing', 'Video Düzenleme', 'Video Editing', 'creative', '🎬', 4),
('graphic-design', 'Grafik Tasarım', 'Graphic Design', 'creative', '✒️', 5),
('animation', 'Animasyon', 'Animation', 'creative', '🏃', 6),
('diy', 'Kendin Yap (DIY)', 'DIY', 'creative', '🛠️', 7),
('calligraphy', 'Kaligrafi', 'Calligraphy', 'creative', '🖋️', 8),
('ceramics', 'Seramik', 'Ceramics', 'creative', '🏺', 9),
('sculpture', 'Heykel', 'Sculpture', 'creative', '🗿', 10),
('music-production', 'Müzik Yapımı', 'Music Production', 'creative', '🎹', 11),
('writing', 'Yazarlık', 'Writing', 'creative', '📝', 12),
('poetry', 'Şiir', 'Poetry', 'creative', '📜', 13),
('cinema', 'Sinema', 'Cinema', 'creative', '🍿', 14),
('theater', 'Tiyatro', 'Theater', 'creative', '🎭', 15),
('standup', 'Stand-Up', 'Stand-Up', 'creative', '🎤', 16),
('podcast', 'Podcast', 'Podcast', 'creative', '🎙️', 17),
('cosplay', 'Cosplay', 'Cosplay', 'creative', '🦸', 18),
('origami', 'Origami', 'Origami', 'creative', '🦢', 19),
('fashion-design', 'Moda Tasarımı', 'Fashion Design', 'creative', '👗', 20),

-- sport (15)
('football', 'Futbol', 'Football', 'sport', '⚽', 1),
('basketball', 'Basketbol', 'Basketball', 'sport', '🏀', 2),
('tennis', 'Tenis', 'Tennis', 'sport', '🎾', 3),
('swimming', 'Yüzme', 'Swimming', 'sport', '🏊', 4),
('running', 'Koşu', 'Running', 'sport', '🏃', 5),
('yoga', 'Yoga', 'Yoga', 'sport', '🧘', 6),
('fitness', 'Fitness', 'Fitness', 'sport', '💪', 7),
('cycling', 'Bisiklet', 'Cycling', 'sport', '🚴', 8),
('mountaineering', 'Dağcılık', 'Mountaineering', 'sport', '🧗', 9),
('boxing', 'Boks', 'Boxing', 'sport', '🥊', 10),
('chess', 'Satranç', 'Chess', 'sport', '♟️', 11),
('esports', 'E-Spor', 'Esports', 'sport', '🎮', 12),
('dance', 'Dans', 'Dance', 'sport', '💃', 13),
('martial-arts', 'Dövüş Sanatları', 'Martial Arts', 'sport', '🥋', 14),
('volleyball', 'Voleybol', 'Volleyball', 'sport', '🏐', 15),

-- entertainment (15)
('anime', 'Anime', 'Anime', 'entertainment', '🎌', 1),
('manga', 'Manga', 'Manga', 'entertainment', '📖', 2),
('marvel-dc', 'Marvel / DC', 'Marvel / DC', 'entertainment', '🦸', 3),
('movies-series', 'Film / Dizi', 'Movies / Series', 'entertainment', '🎬', 4),
('netflix', 'Netflix', 'Netflix', 'entertainment', '📺', 5),
('k-drama', 'K-Drama', 'K-Drama', 'entertainment', '🎭', 6),
('harry-potter', 'Harry Potter', 'Harry Potter', 'entertainment', '⚡', 7),
('star-wars', 'Star Wars', 'Star Wars', 'entertainment', '⚔️', 8),
('tolkien-lotr', 'Tolkien / LOTR', 'Tolkien / LOTR', 'entertainment', '🧝', 9),
('studio-ghibli', 'Studio Ghibli', 'Studio Ghibli', 'entertainment', '🐉', 10),
('documentary', 'Belgesel', 'Documentary', 'entertainment', '🌍', 11),
('reality-show', 'Reality Show', 'Reality Show', 'entertainment', '🤩', 12),
('webtoon', 'Webtoon', 'Webtoon', 'entertainment', '📱', 13),
('space-cosmos', 'Uzay / Kozmos', 'Space / Cosmos', 'entertainment', '🌌', 14),
('true-crime', 'Gerçek Suç', 'True Crime', 'entertainment', '🕵️', 15),

-- lifestyle (15)
('study-with-me', 'Benimle Çalış', 'Study With Me', 'lifestyle', '📚', 1),
('cooking', 'Yemek / Aşçılık', 'Cooking', 'lifestyle', '🍳', 2),
('travel', 'Seyahat', 'Travel', 'lifestyle', '✈️', 3),
('meditation', 'Meditasyon', 'Meditation', 'lifestyle', '🧘', 4),
('minimalism', 'Minimalizm', 'Minimalism', 'lifestyle', '🤍', 5),
('bullet-journal', 'Bullet Journal', 'Bullet Journal', 'lifestyle', '📓', 6),
('reading', 'Okuma', 'Reading', 'lifestyle', '📖', 7),
('coffee-culture', 'Kahve Kültürü', 'Coffee Culture', 'lifestyle', '☕', 8),
('sustainability', 'Sürdürülebilirlik', 'Sustainability', 'lifestyle', '♻️', 9),
('volunteering', 'Gönüllülük', 'Volunteering', 'lifestyle', '🤝', 10),
('personal-development', 'Kişisel Gelişim', 'Personal Development', 'lifestyle', '🌱', 11),
('pets', 'Evcil Hayvanlar', 'Pets', 'lifestyle', '🐾', 12),
('plant-care', 'Bitki Bakımı', 'Plant Care', 'lifestyle', '🪴', 13),
('astrology', 'Astroloji', 'Astrology', 'lifestyle', '✨', 14),
('entrepreneurship', 'Girişimcilik', 'Entrepreneurship', 'lifestyle', '💡', 15),

-- hobby (10)
('dnd', 'D&D', 'Dungeons & Dragons', 'hobby', '🐉', 1),
('puzzle', 'Bulmaca / Puzzle', 'Puzzle', 'hobby', '🧩', 2),
('lego', 'Lego', 'Lego', 'hobby', '🧱', 3),
('model-building', 'Model Yapımı', 'Model Building', 'hobby', '✈️', 4),
('card-games', 'Kart Oyunları', 'Card Games', 'hobby', '🃏', 5),
('board-games', 'Masa Oyunları', 'Board Games', 'hobby', '🎲', 6),
('collecting', 'Koleksiyon', 'Collecting', 'hobby', '🪙', 7),
('retro-games', 'Retro Oyunlar', 'Retro Games', 'hobby', '🕹️', 8),
('quiz-trivia', 'Bilgi Yarışması', 'Quiz / Trivia', 'hobby', '❓', 9),
('rubik-cube', 'Rubik Küpü', 'Rubik Cube', 'hobby', '🧊', 10),

-- music (added 10)
('acoustic', 'Akustik', 'Acoustic', 'music', '🎸', 21),
('soul', 'Soul', 'Soul', 'music', '🎷', 22),
('funk', 'Funk', 'Funk', 'music', '🕺', 23),
('disco', 'Disko', 'Disco', 'music', '🪩', 24),
('techno', 'Tekno', 'Techno', 'music', '🔊', 25),
('house', 'House', 'House', 'music', '🏠', 26),
('ambient', 'Ambient', 'Ambient', 'music', '☁️', 27),
('opera', 'Opera', 'Opera', 'music', '🎭', 28),
('gospel', 'Gospel', 'Gospel', 'music', '🙌', 29),
('salsa', 'Salsa', 'Salsa', 'music', '💃', 30),

-- language (added 10)
('hindi-urdu', 'Hintçe / Urduca', 'Hindi / Urdu', 'language', '🗣️', 26),
('indonesian', 'Endonezyaca', 'Indonesian', 'language', '🇮🇩', 27),
('tagalog', 'Tagalogca', 'Tagalog', 'language', '🇵🇭', 28),
('swahili', 'Svahili', 'Swahili', 'language', '🌍', 29),
('hebrew', 'İbranice', 'Hebrew', 'language', '🇮🇱', 30),
('finnish', 'Fince', 'Finnish', 'language', '🇫🇮', 31),
('norwegian', 'Norveççe', 'Norwegian', 'language', '🇳🇴', 32),
('danish', 'Danca', 'Danish', 'language', '🇩🇰', 33),
('klingon', 'Klingonca', 'Klingon', 'language', '👽', 34),
('sign-language', 'İşaret Dili', 'Sign Language', 'language', '🤟', 35),

-- subject (added 10)
('computer-science', 'Bilgisayar Bilimi', 'Computer Science', 'subject', '💻', 31),
('botany', 'Botanik', 'Botany', 'subject', '🌿', 32),
('zoology', 'Zooloji', 'Zoology', 'subject', '🦓', 33),
('paleontology', 'Paleontoloji', 'Paleontology', 'subject', '🦖', 34),
('meteorology', 'Meteoroloji', 'Meteorology', 'subject', '⛈️', 35),
('geology', 'Jeoloji', 'Geology', 'subject', '🪨', 36),
('theology', 'Teoloji', 'Theology', 'subject', '📖', 37),
('mythology', 'Mitoloji', 'Mythology', 'subject', '⚡', 38),
('education', 'Eğitim', 'Education', 'subject', '🏫', 39),
('journalism', 'Gazetecilik', 'Journalism', 'subject', '📰', 40),

-- tech (added 10)
('typescript', 'TypeScript', 'TypeScript', 'tech', '🟦', 26),
('ruby', 'Ruby', 'Ruby', 'tech', '♦️', 27),
('php', 'PHP', 'PHP', 'tech', '🐘', 28),
('go', 'Go', 'Go', 'tech', '🐹', 29),
('rust', 'Rust', 'Rust', 'tech', '⚙️', 30),
('csharp', 'C#', 'C#', 'tech', '🔷', 31),
('html-css', 'HTML / CSS', 'HTML / CSS', 'tech', '🎨', 32),
('aws', 'AWS', 'AWS', 'tech', '☁️', 33),
('docker', 'Docker', 'Docker', 'tech', '🐳', 34),
('kubernetes', 'Kubernetes', 'Kubernetes', 'tech', '☸️', 35),

-- creative (added 10)
('makeup', 'Makyaj', 'Makeup', 'creative', '💄', 21),
('nail-art', 'Nail Art', 'Nail Art', 'creative', '💅', 22),
('interior-design', 'İç Mimarlık', 'Interior Design', 'creative', '🛋️', 23),
('architecture-design', 'Mimari Tasarım', 'Architecture Design', 'creative', '🏗️', 24),
('knitting', 'Örgü / Tığ', 'Knitting / Crochet', 'creative', '🧶', 25),
('sewing', 'Dikiş', 'Sewing', 'creative', '🪡', 26),
('woodworking', 'Ahşap İşçiliği', 'Woodworking', 'creative', '🪚', 27),
('metalworking', 'Metal İşçiliği', 'Metalworking', 'creative', '⚒️', 28),
('glassblowing', 'Cam Üfleme', 'Glassblowing', 'creative', '🔥', 29),
('jewelry-making', 'Takı Tasarımı', 'Jewelry Making', 'creative', '💍', 30),

-- sport (added 10)
('badminton', 'Badminton', 'Badminton', 'sport', '🏸', 16),
('table-tennis', 'Masa Tenisi', 'Table Tennis', 'sport', '🏓', 17),
('golf', 'Golf', 'Golf', 'sport', '⛳', 18),
('baseball', 'Beyzbol', 'Baseball', 'sport', '⚾', 19),
('rugby', 'Ragbi', 'Rugby', 'sport', '🏉', 20),
('cricket', 'Kriket', 'Cricket', 'sport', '🏏', 21),
('ice-hockey', 'Buz Hokeyi', 'Ice Hockey', 'sport', '🏒', 22),
('skiing', 'Kayak', 'Skiing', 'sport', '⛷️', 23),
('snowboarding', 'Snowboard', 'Snowboarding', 'sport', '🏂', 24),
('surfing', 'Sörf', 'Surfing', 'sport', '🏄', 25),

-- entertainment (added 10)
('sitcom', 'Sitcom', 'Sitcom', 'entertainment', '🛋️', 16),
('sci-fi', 'Bilim Kurgu', 'Sci-Fi', 'entertainment', '👽', 17),
('fantasy', 'Fantastik', 'Fantasy', 'entertainment', '🐉', 18),
('thriller', 'Gerilim', 'Thriller', 'entertainment', '🔪', 19),
('horror', 'Korku', 'Horror', 'entertainment', '👻', 20),
('comedy', 'Komedi', 'Comedy', 'entertainment', '😂', 21),
('drama', 'Dram', 'Drama', 'entertainment', '🎭', 22),
('action', 'Aksiyon', 'Action', 'entertainment', '💥', 23),
('romance', 'Romantik', 'Romance', 'entertainment', '❤️', 24),
('animation-movie', 'Animasyon Film', 'Animation Movie', 'entertainment', '🎨', 25),

-- lifestyle (added 10)
('veganism', 'Vegan Yaşam', 'Veganism', 'lifestyle', '🥗', 16),
('vegetarianism', 'Vejetaryen', 'Vegetarianism', 'lifestyle', '🥦', 17),
('fitness-lifestyle', 'Sağlıklı Yaşam', 'Healthy Lifestyle', 'lifestyle', '🥑', 18),
('digital-nomad', 'Dijital Göçebe', 'Digital Nomad', 'lifestyle', '💻', 19),
('van-life', 'Karavan Hayatı', 'Van Life', 'lifestyle', '🚐', 20),
('homesteading', 'Kendi Kendine Yetme', 'Homesteading', 'lifestyle', '🏡', 21),
('parenting', 'Ebeveynlik', 'Parenting', 'lifestyle', '👶', 22),
('spirituality', 'Maneviyat', 'Spirituality', 'lifestyle', '✨', 23),
('productivity', 'Üretkenlik', 'Productivity', 'lifestyle', '⏱️', 24),
('finance', 'Kişisel Finans', 'Personal Finance', 'lifestyle', '💰', 25),

-- hobby (added 10)
('magic-tricks', 'Sihirbazlık', 'Magic Tricks', 'hobby', '🎩', 11),
('juggling', 'Hokkabazlık', 'Juggling', 'hobby', '🤹', 12),
('bird-watching', 'Kuş Gözlemciliği', 'Bird Watching', 'hobby', '🦅', 13),
('astronomy-hobby', 'Amatör Astronomi', 'Amateur Astronomy', 'hobby', '🔭', 14),
('foraging', 'Doğadan Toplayıcılık', 'Foraging', 'hobby', '🍄', 15),
('aquarium', 'Akvaryum', 'Aquarium', 'hobby', '🐠', 16),
('bonsai', 'Bonsai', 'Bonsai', 'hobby', '🌳', 17),
('calligraphy-hobby', 'Hat Sanatı', 'Calligraphy', 'hobby', '🖋️', 18),
('scrapbooking', 'Scrapbooking', 'Scrapbooking', 'hobby', '📔', 19),
('lockpicking', 'Kilit Açma', 'Lockpicking', 'hobby', '🔓', 20);
